version: "3.9"

services:
  db:
    container_name: testContainer
    image: postgres:alpine
    ports:
      - 5435:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=mix


volumes:
  postgres_data: